### PR TITLE
Add expire command to remove old SourceFiles and Grants

### PR DESCRIPTION
**Pull request by Bjwebb**

### CODE REVIEW

**Comment by Bjwebb** [comment]
@michaelwood I've reworked this to add a Grant.dataset check as discussed.

Note:
1) This is currently the command `flask expire expire`. I'm not sure if we want to rename that, or whether it's a done thing to have an ungrouped command like `flask expire`.
2) This does 2 delete queries for each source file. But, so did the previous code. And, I don't think we'll have so many source files that this is a problem.
3) Although grants with dataset main won't be deleted, the associated source files will be if they lack a publisher prefix.

**Comment by michaelwood** [comment]
> @michaelwood I've reworked this to add a Grant.dataset check as discussed.
> 
> Note:
> 
> 1. This is currently the command `flask expire expire`. I'm not sure if we want to rename that, or whether it's a done thing to have an ungrouped command like `flask expire`.

I think it's a good idea to have the command grouped, but agree if we can avoid `expire expire` that would be good. We will document this command and it will be added to cron so would be good to change it now if you have the energy for that.

Some ideas:
flask data expire_uploaded
flask expire uploaded_data [possible future argument --older-than 7]

**Review by michaelwood — APPROVED** [review]
Approved (optional requested change)

**Comment by Bjwebb** [comment]
I've renamed to "expire uploaded_data".

**Pull request merged**
