### PR TITLE
templates: data-display: replace 'Average Grant' with 'Funders' on top

### PR DESCRIPTION
**Pull request by BibianaC**
relates to #144

### CODE REVIEW

**Review by michaelwood — CHANGES_REQUESTED** [review]
Maybe a commit missing as I don't see any backend work here to add the funders_total that you're referencing. 

I also think the funders should be a black highlight instead of yellow as that's what we've used on the quality dashboard. https://qualitydashboard.threesixtygiving.org/

**Comment by BibianaC** [comment]
@michaelwood I did check the results page locally (I can't check the homepage) and it does give me a number. I thought it was the correct one as if I select one funder it appears just one.
One issue though that I don't know if it would appear when deployed is that when the page is loading all the boxes have a "0" and in the Funders is a "NaN".

@KDuerden you suggested keeping `Funders` in yellow but Michael is suggesting changing it to black to match the colour used on the dashboard. Is that okay with you?

**Comment by KDuerden** [comment]
> @KDuerden you suggested keeping `Funders` in yellow but Michael is suggesting changing it to black to match the colour used on the dashboard. Is that okay with you?

Yes, that makes sense - thanks for suggesting that.

**Comment by BibianaC** [comment]
Thanks, @KDuerden.

@michaelwood I have changed the colour to black.

**Comment by michaelwood** [comment]
Can you tell me where the value for `datasetSelect.dataset_stats.funders_total` comes from?

**Comment by Lathrisk** [comment]
Current mages for reference:
Filtered dataset:
funders-update-data
Homepage:
funder-update

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
